### ISSUE TITLE
No download URL.

### ISSUE THREAD

**Issue by yodaluca23** [QuarkSources/quarksources.github.io#4]
All the apps no longer specify a download url for the apps, only the specific versions, this causes for some software, like Scarlet not to be able to let you download any of the apps because it can't find a download URL.

**Comment by noah978** [comment]
I will be supporting legacy versions of the AltSource API to an extent, but eventually, expect them to no longer include all legacy tags. Each extra bit of legacy data slows down the speed of source update calls.
