### ISSUE TITLE
Error when adding source Q+

### ISSUE THREAD

**Issue by kcheff** [QuarkSources/quarksources.github.io#8]
I get a "Error fetching JSON: Network Error" when trying to add Quantum Plus to Flekstore (Altstore Sources are the only supported source)![image](https://github.com/QuarkSources/quarksources.github.io/assets/116896390/44531e64-bece-48d3-847e-0dd5be38a388)

**Comment by noah978** [comment]
I’m guessing there’s just an issue with flekstore using a very outdated version of the AltSource API. I am supporting legacy versions of the API to an extent, but I won’t be investigating this one
